# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3834e5f83d0eb46d57f9f927140278ed75a5301ea48bc88765723498e125317ea204be83452d1847d7eb5760a4652290a9c35b86893a7d3a8dc9bdcfb1386b23

test:
  secret_key_base: 8eff00665d3097629177c64222ddb2abecfcc6de8f45091d471a9f65b90ddf442df33236da66637b59dce5b253bc04893b6e29e76b33e2a1542c2c31c4210ac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
